include classpath("application.conf")

queues {
  analysis-tasks {
    defaultVisibilityTimeout = 180 seconds
    receiveMessageWait = 20 seconds
    deadLettersQueue {
      name = "analysis-tasks-dlq"
      maxReceiveCount = 5
    }
  }
  analysis-tasks-dlq {}
}
